#!/usr/bin/env bash
# =============================================================================
# deploy-dockerfiles.sh
# Creates a standard layered-JAR Dockerfile inside each of the 8 service
# directories. Run this from the ROOT of spring-petclinic-microservices/.
#
# The Dockerfile template is EMBEDDED in this script (heredoc) — no external
# file path needed, no path dependency issues.
#
# Usage:
#   cd spring-petclinic-microservices/
#   bash ../scripts/deploy-dockerfiles.sh
#       OR (if scripts/ is copied inside the repo):
#   bash ./scripts/deploy-dockerfiles.sh
# =============================================================================
set -euo pipefail

# ── Port mapping per service ──────────────────────────────────────────────────
declare -A SERVICE_PORTS=(
  ["spring-petclinic-config-server"]="8888"
  ["spring-petclinic-discovery-server"]="8761"
  ["spring-petclinic-api-gateway"]="8080"
  ["spring-petclinic-customers-service"]="8081"
  ["spring-petclinic-visits-service"]="8082"
  ["spring-petclinic-vets-service"]="8083"
  ["spring-petclinic-admin-server"]="9090"
  ["spring-petclinic-genai-service"]="8084"
)

# ── Verify we are in the right directory ──────────────────────────────────────
# At least one service directory must exist — safeguard against running from
# the wrong location.
if [[ ! -d "./spring-petclinic-config-server" ]]; then
  echo "ERROR: Run this script from the ROOT of spring-petclinic-microservices/"
  echo "       Current directory: $(pwd)"
  echo "       Expected to find: ./spring-petclinic-config-server/"
  exit 1
fi

echo "Working directory: $(pwd)"
echo "Deploying Dockerfiles to all service directories..."
echo ""

CREATED=0
SKIPPED=0
MISSING=0

for SERVICE in "${!SERVICE_PORTS[@]}"; do
  PORT="${SERVICE_PORTS[$SERVICE]}"
  DEST="./${SERVICE}/Dockerfile"

  # ── Service directory must exist ────────────────────────────────────────────
  if [[ ! -d "./${SERVICE}" ]]; then
    echo "  SKIP    ${SERVICE}/ — directory not found"
    (( MISSING++ )) || true
    continue
  fi

  # ── Don't overwrite existing Dockerfiles ───────────────────────────────────
  if [[ -f "${DEST}" ]]; then
    echo "  EXISTS  ${SERVICE}/Dockerfile — skipping (delete it first to regenerate)"
    (( SKIPPED++ )) || true
    continue
  fi

  # ── Write the Dockerfile using a heredoc — no external template needed ──────
  cat > "${DEST}" <<DOCKERFILE
# ============================================================================
# Dockerfile — ${SERVICE}
# Generated by deploy-dockerfiles.sh
# Uses Spring Boot layered JARs for optimal Docker layer caching.
# ============================================================================

# Stage 1: Extract Spring Boot JAR layers
FROM eclipse-temurin:21-jre-alpine AS builder
WORKDIR /app
ARG JAR_FILE=target/*.jar
COPY \${JAR_FILE} app.jar
RUN java -Djarmode=layertools -jar app.jar extract

# Stage 2: Minimal runtime image
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Run as non-root for security
RUN addgroup -S petclinic && adduser -S petclinic -G petclinic
USER petclinic

# Copy layers from most stable (deps) to least stable (app code)
COPY --from=builder /app/dependencies/          ./
COPY --from=builder /app/spring-boot-loader/    ./
COPY --from=builder /app/snapshot-dependencies/ ./
COPY --from=builder /app/application/           ./

EXPOSE ${PORT}

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT ["sh", "-c", "java \${JAVA_OPTS} org.springframework.boot.loader.launch.JarLauncher"]
DOCKERFILE

  echo "  CREATED  ${SERVICE}/Dockerfile  (port ${PORT})"
  (( CREATED++ )) || true
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  Done."
echo "  Created : ${CREATED}"
echo "  Skipped : ${SKIPPED}  (already existed)"
echo "  Missing : ${MISSING}  (service directory not found)"
echo "============================================================"

if [[ ${CREATED} -gt 0 ]]; then
  echo ""
  echo "Next steps:"
  echo "  1. git add spring-petclinic-*/Dockerfile"
  echo "  2. git commit -m 'ci: add layered-JAR Dockerfiles for all services'"
  echo "  3. git push origin main"
  echo "  4. Run: bash ./scripts/build-and-push.sh"
fi
